name: AppImage CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build AppImage
    #Ubuntu 16.04 use glibc 2.23
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup QT environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.0-xenial -y
        sudo apt-get update -qq
        sudo apt --assume-yes install \
          build-essential \
          libgl1-mesa-dev \
          qt512base \
          wget
    - name: Build AppImage
      run: |
        mv ./ngPost.desktop ./src
        cd src
        ls -ltrah
        /opt/qt512/bin/qmake
        make
        wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt-continuous-x86_64.AppImage
        ls -ltrah
        ./linuxdeployqt-continuous-x86_64.AppImage ./ngPost.desktop -appimage -qmake=/opt/qt512/bin/qmake
        ls -ltrah
        # Remove trash
        rm -rf ./hmi
        rm -rf ./lang
        rm -rf ./nntp
        rm -rf ./resources
        rm -rf ./utils
        rm -rf ./linuxdeployqt-continuous-x86_64.AppImage
        find ./ \( -name "moc_*" -or -name "*.o" -or -name "*.h" -or -name "*.cpp" -or -name "qrc_*" -or -name "Makefile*" -or -name "*.a" \) -exec rm -rf {} \;
    - name: Create Release
      id: create_release
      uses: meeDamian/github-release@2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: continuous
        name: Continuous build
        body: |
          Release ${{ github.sha }}
        files: ./src/ngPost-*-x86_64.AppImage/ngPost-*-x86_64.AppImage
        draft: false
        prerelease: true
        allow_override: true
